pipeline{
agent any
stages{
stage('Build'){
    agent none {
        docker{image 'maven'}
        }
        steps{
        sh "mvn packege - Dmaven.test.skip=true"
        }
    }
    }
        }



